### ISSUE TITLE
Warning in production logs, reference has gone stale

### ISSUE THREAD

**Issue by somesh-kumar** [eclipse/vorto#1684]
Repeated warning observed in production logs.

2019-06-24 09:32:20.475  WARN 27687 --- [nio-8080-exec-5] o.e.v.r.core.impl.JcrModelRepository     : A reference has gone stale. Please remove this reference. : 

org.modeshape.jcr.cache.NodeNotFoundInParentException: Cannot locate child node: af55b687505d64e57680e0-205c-4fb4-bbde-0822aab371a5 within parent: af55b687505d640534644e-d733-45cd-8a77-0f90aa6b066b
	at org.modeshape.jcr.cache.document.LazyCachedNode.parentReferenceToSelf(LazyCachedNode.java:247) ~[modeshape-jcr-4.3.0.Final.jar!/:4.3.0.Final]
	at org.modeshape.jcr.cache.document.LazyCachedNode.getSegment(LazyCachedNode.java:284) ~[modeshape-jcr-4.3.0.Final.jar!/:4.3.0.Final]
	at org.modeshape.jcr.cache.document.LazyCachedNode.getPath(LazyCachedNode.java:293) ~[modeshape-jcr-4.3.0.Final.jar!/:4.3.0.Final]
	at org.modeshape.jcr.cache.document.LazyCachedNode.getPath(LazyCachedNode.java:292) ~[modeshape-jcr-4.3.0.Final.jar!/:4.3.0.Final]
	at org.modeshape.jcr.cache.document.LazyCachedNode.getPath(LazyCachedNode.java:292) ~[modeshape-jcr-4.3.0.Final.jar!/:4.3.0.Final]
	at org.modeshape.jcr.AbstractJcrNode.path(AbstractJcrNode.java:225) ~[modeshape-jcr-4.3.0.Final.jar!/:4.3.0.Final]

**Comment by somesh-kumar** [comment]
@aedelmann, please prioritize

**Comment by aedelmann** [comment]
Cannot reproduce with latest version
