### ISSUE TITLE
Don't create tenant workspace if it already exists on startup

### ISSUE THREAD

**Issue by hristobojilov** [eclipse/vorto#1757]
After restart of Vorto repo I'm getting this error:
```
RepositoryManager      : Exception while creating workspace
javax.jcr.RepositoryException: The workspace "standardization" already exists in the "default" repository
        at org.modeshape.jcr.JcrWorkspace.createWorkspace(JcrWorkspace.java:779) ~[modeshape-jcr-4.3.0.Final.jar!/:4.3.0.Final]
        at org.eclipse.vorto.repository.core.impl.RepositoryManager.createTenantWorkspace(RepositoryManager.java:85) ~[repository-core-0.11.0-SNAPSHOT.ja
r!/:na]
        at org.eclipse.vorto.repository.core.impl.ModelRepositoryEventListener.createWorkspaceForTenant(ModelRepositoryEventListener.java:66) [repository
-core-0.11.0-SNAPSHOT.jar!/:na]
        at org.eclipse.vorto.repository.core.impl.ModelRepositoryEventListener.onApplicationEvent(ModelRepositoryEventListener.java:49) [repository-core-
0.11.0-SNAPSHOT.jar!/:na]
```
and it can't started anymore without database cleanup.

**Comment by erlemantos** [comment]
This is indeed a bug. I'm on this.

**Comment by aedelmann** [comment]
Fixed and merged into development
