### ISSUE TITLE
Cannot import model with references to unknown namespace

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1877]
Steps to reproduce:

1. Login 
2. Click import
3. Choose information model which has reference to a namespace, which does not exist in repository, e.g. "com.ipso"
4. Click Upload
Expected: proper error message saying sth like "invalid reference error"
Actual: Internal server error

Stacktrace:

java.lang.NullPointerException: null
	at org.eclipse.vorto.repository.core.impl.parser.AbstractModelParser.lambda$importDependenciesFromRepository$9(AbstractModelParser.java:163) ~[repository-core-0.11.2.jar!/:na]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_201]
	at org.eclipse.vorto.repository.core.impl.parser.AbstractModelParser.importDependenciesFromRepository(AbstractModelParser.java:162) ~[repository-core-0.11.2.jar!/:na]
	at org.eclipse.vorto.repository.core.impl.parser.AbstractModelParser.parse(AbstractModelParser.java:95) ~[repository-core-0.11.2.jar!/:na]
	at org.eclipse.vorto.repository.importer.AbstractModelImporter.parseDSL(AbstractModelImporter.java:324) ~[repository-core-0.11.2.jar!/:na]
	at org.eclipse.vorto.repository.importer.AbstractModelImporter.parseDSL(AbstractModelImporter.java:314) ~[repository-core-0.11.2.jar!/:na]
	at org.eclipse.vorto.repository.importer.impl.VortoModelImporter.validate(VortoModelImporter.java:147) ~[repository-core-0.11.2.jar!/:na]
	at org.eclipse.vorto.repository.importer.AbstractModelImporter.upload(AbstractModelImporter.java:116) ~[repository-core-0.11.2.jar!/:na]
	at org.eclipse.vorto.repository.web.importer.ImportController.uploadModel(ImportController.java:91) ~[repository-core-0.11.2.jar!/:na]
	at org.eclipse.vorto.repository.web.importer.ImportController$$FastClassBySpringCGLIB$$33dbef4a.invoke(<generated>) ~[repository-core-0.11.2.jar!/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736) ~[spring-aop-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69) ~[spring-security-core-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671) ~[spring-aop-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.eclipse.vorto.repository.web.importer.ImportController$$EnhancerBySpringCGLIB$$ee6d4155.uploadModel(<generated>) ~[repository-core-0.11.2.jar!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandler

**Comment by MayilKannanKumarBosch** [comment]
I am working on this...
