### ISSUE TITLE
Custom Error Page does not work on the Dev environment

### ISSUE THREAD

**Issue by kolotu** [eclipse/vorto#2206]
The custom error page is not displayed on the Dev environment, instead the Tomcat default error page is shown. 
Error in the logs: 

```
2020-01-09 06:58:14.390 ERROR 477 --- [nio-8080-exec-9] o.e.v.repository.web.VortoErrorHandler   : Exception while loading the error page HTML template

java.io.FileNotFoundException: file:/var/app/current/application.jar!/BOOT-INF/classes!/static/error/error-template.html (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_222]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_222]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_222]
	at java.io.FileReader.<init>(FileReader.java:72) ~[na:1.8.0_222]
	at org.eclipse.vorto.repository.web.VortoErrorHandler.readHtmlTemplate(VortoErrorHandler.java:73) [classes!/:na]
```

**Comment by kolotu** [comment]
Fixed.
