### ISSUE TITLE
Sporadic occurrence of NPE in stack traces in productive environments

### ISSUE THREAD

**Issue by mena-bosch** [eclipse/vorto#2706]
We can observe the occurrence of traces displaying:

```
java.lang.NullPointerException: null
    at org.eclipse.vorto.repository.conversion.ModelIdToModelContentConverter.convert(ModelIdToModelContentConverter.java:56) ~[repository-core-1.0.1-SNAPSHOT.jar!/:na]
    at org.eclipse.vorto.repository.web.api.v1.ModelController.getModelContent(ModelController.java:80) ~[repository-core-1.0.1-SNAPSHOT.jar!/:na]
   [etc...]
 ```

While the top trace element points to an obvious suspect, none of the objects _should_ be `null` at that point. 

Would need to replicate consistently and find the root cause.

**Comment by kolotu** [comment]
The root cause seems to be calling the API with a non-existing namespace - instead of returning a 404 message, it throws a NPE and returns HTTP 500.

`/api/v1/models/<ModelID>/content`

**Comment by kolotu** [comment]
Fixed https://github.com/eclipse/vorto/pull/2727
