### ISSUE TITLE
Setup Vorto Repository as Docker Container on Eclipse VM

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#500]
Confirmations:
- Set classpath variables:
-- mysql-connector-java.jar Version: 5.1.37 (MySQL driver)
-- infinispan.xml containing mqsql configuration for existing mysql db on VM
-- repository-mysql.json Modeshape configuration for existing mysql db on VM
- Docker pull and run with the variables in docker-compose.xml (containing the generators also)

**Comment by vlvanchin** [comment]
@aedelmann  it seems that the -cp or -classpath variables will be ignored when we run java with -jar option. hence we may need to modify the manifest.mf to have the Class-path pointed to the mysql-connection-java.jar location.

**Comment by vlvanchin** [comment]
Tried modifying the manifest.mf file by adding Class-path header in the following two ways 
* adding Class-path: jar-name
-- Class-Path: mysql-connector-java-5.1.37.jar
* adding Class-path: dir/jar-name
-- Class-Path: lib/mysql-connector-java-5.1.37.jar

Executing the repository jar in both the scenarios lead to the following error

{code}
$ Exception in thread "main" java.lang.IllegalStateException: Unable to open nested entry 'BOOT-INF/lib/tomcat-embed-logging-juli-8.0.28.jar'. It has been compressed and nested jar files must be stored without compression. Please check the mechanism used to create your executable jar file
	at org.springframework.boot.loader.jar.JarFile.createJarFileFromFileEntry(JarFile.java:285)
	at org.springframework.boot.loader.jar.JarFile.createJarFileFromEntry(JarFile.java:260)
	at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:248)
	at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:237)
	at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:103)
	at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchives(JarFileArchive.java:87)
	at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:72)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:49)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)



{code}
